version: '3'

services:
  web:
    build: .
    hostname: web
    command: bash -c "python manage.py migrate && gunicorn example.wsgi:application --workers 3 --bind unix:/app/example.sock"
    volumes:
      - ./src:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
    volumes:
      - ./src:/app
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web